export const ROLES = {
  ADMIN: 'admin',
  MANAGER: 'manager',
  PROCUREMENT_OFFICER: 'procurement_officer',
  VENDOR: 'vendor',
};

export const PERMISSIONS = {
  CREATE_RFQ: [ROLES.ADMIN, ROLES.PROCUREMENT_OFFICER],
  COMPARE_QUOTATIONS: [ROLES.ADMIN, ROLES.PROCUREMENT_OFFICER],
  SUBMIT_QUOTATION: [ROLES.VENDOR],
  APPROVE_REQUEST: [ROLES.ADMIN, ROLES.MANAGER],
  GENERATE_PO: [ROLES.ADMIN, ROLES.PROCUREMENT_OFFICER],
  GENERATE_INVOICE: [ROLES.ADMIN, ROLES.PROCUREMENT_OFFICER],
  SEND_INVOICE_EMAIL: [ROLES.ADMIN, ROLES.PROCUREMENT_OFFICER],
  MANAGE_VENDORS: [ROLES.ADMIN],
  VIEW_REPORTS: [ROLES.ADMIN, ROLES.MANAGER],
  VIEW_ACTIVITY_LOGS: [ROLES.ADMIN, ROLES.MANAGER],
};
