export const ROLES = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  PROCUREMENT_OFFICER: 'PROCUREMENT_OFFICER',
  VENDOR: 'VENDOR',
};

export const PERMISSIONS = {
  CREATE_RFQ: [ROLES.ADMIN, ROLES.PROCUREMENT_OFFICER],
  COMPARE_QUOTATIONS: [ROLES.ADMIN, ROLES.PROCUREMENT_OFFICER],
  SUBMIT_QUOTATION: [ROLES.VENDOR],
  APPROVE_REQUEST: [ROLES.ADMIN, ROLES.MANAGER],
  GENERATE_PO: [ROLES.ADMIN, ROLES.PROCUREMENT_OFFICER],
  GENERATE_INVOICE: [ROLES.ADMIN, ROLES.PROCUREMENT_OFFICER],
  SEND_INVOICE_EMAIL: [ROLES.ADMIN, ROLES.PROCUREMENT_OFFICER],
  MANAGE_VENDORS: [ROLES.ADMIN],
  VIEW_REPORTS: [ROLES.ADMIN, ROLES.MANAGER],
  VIEW_ACTIVITY_LOGS: [ROLES.ADMIN, ROLES.MANAGER, ROLES.PROCUREMENT_OFFICER],
};
